queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label!=do-not-merge
      - "#approved-reviews-by>=1"
      - or:
          - "title~=^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"
          - and:
              - "title~=^Bump .+"
              - author=dependabot[bot]
    merge_conditions: []
    merge_method: rebase
    update_method: rebase
defaults:
  actions:
    queue:
      name: default

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - label!=do-not-merge
      - "#approved-reviews-by>=1"
      - or:
          - "title~=^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"
          - and:
              - "title~=^Bump .+"
              - author=dependabot[bot]
    actions:
      delete_head_branch: {}
      queue:
    
#  - name: Automatic approval for Dependabot pull requests
#    conditions:
#      - author=dependabot[bot]
#    actions:
#      review:
#        type: APPROVE
#        message: Automatically approving dependabot

  - name: Remove outdated reviews for non trusted authors
    conditions:
      - base=main
      - author!=m3nax
    actions:
      dismiss_reviews:
  - name: Ask to resolve conflict
    conditions:
      - conflict
      - author!=dependabot[bot]
    actions:
      comment:
        message: This pull request is now in conflicts with the target branch. Could
          you fix it @{{author}}? 🙏
