defaults:
  actions:
    queue:
      name: default
      method: rebase
      update_method: rebase
      # For rebasing Mergify uses the author of the PR.

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - label!=do-not-merge
      - "#approved-reviews-by>=1"
      - "approved-reviews-by=@m3nax"
    actions:
      queue:
        name: default
      delete_head_branch: {}
      
  - name: Check conventional commit
    conditions:
      - base=main
    actions:
      post_check:
        success_conditions:
          - "title~=^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"
        title: |
          {% if check_succeed %}
          Title follows Conventional Commit
          {% else %}
          Title does not follow Conventional Commit
          {% endif %}
        summary: |
          {% if not check_succeed %}
          Your pull request title must follow [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/).
          {% endif %}
        
  - name: Ask to resolve conflict
    conditions:
      - conflict
      - author!=dependabot[bot]
    actions:
        comment:
          message: This pull request is now in conflicts with the target branch. Could you fix it @{{author}}? 🙏
